# 端口号
server:
  port: 8201

#基础配置文件
spring:
  application:
    name: user-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver     # 数据库驱动
      url: jdbc:mysql://127.0.0.1/mybatis?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false     # 数据库链接
      username: root     # 数据库账号
      password: 123456     # 数据库密码
    devtools:
      restart:
        enabled: true     # 开启热更新

##eurka配置
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8001/eureka/

mybatis-plus:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.bobby.cloud.mapper: DEBUG

